version: '3'

services:
  nemaki-setup-ui:
    image: maven:3.6-jdk-8
    # image: mozilla/sbt
    #image: frolvlad/alpine-scala
    #build: ./nemaki-setup-ui
    #image: openjdk:8-jre-alpine
    volumes:
      - ./nemaki-setup-ui/repositories:/root/.sbt/repositories
      - ./nemaki-setup-ui/setup.sh:/home/scripts/setup.sh
      - ./../../../ui/activator-launch-1.2.10.jar:/root/.ivy2/local/com.typesafe.activator/activator-launcher/1.2.10/jars/activator-launcher.jar
      - ./../../../:/home/app/
    tty: true
    command: /home/scripts/setup.sh
  # nemaki-setup-mvn:
  #   image: maven:3.6-jdk-8
  #   volumes: 
  #     - ./nemaki-setup-core/scripts/:/home/scripts/
  #     - ./../../../:/home/app
  #   tty: true