version: '3'

services:
  # nemakidev-couchdb:
  #   image: apache/couchdb:2.3.1
  #   ports:
  #     - 5984:5984
  #   environment:
  #     - COUCHDB_USER=admin
  #     - COUCHDB_PASSWORD=password
      
  # nemakidev-ui:
  #   build: ../../../
  #   volumes:
  #     - ./../../../:/app
  #   ports:
  #     - 8080:8080
  #     - 8888:8888
  #   command: /bin/bash
  #   tty: yes
  # nemakidev-core:
  #   build: ../../../
  #   volumes:
  #     - ./../../../:/app
  #     - ./dependencies:/dependencies
  #   ports:
  #     - 8081:8080
  #   command: /bin/bash
  #   tty: yes
      
  nemakidev-solr:
    build: ./image
    volumes:
      - ./../../../:/app
    ports:
      - 8082:8080
    command: /bin/bash
    tty: yes