version: '3'

services:
  nemakidev-couchdb:
    image: apache/couchdb:2.3.1
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./db/data:/opt/couchdb/data
  nemakidev:
    image: aegif/nemakibuild
    volumes:
      - ./../../../:/app
      - ./dep/ivy2:/root/.ivy2
      - ./dep/sbt:/root/.sbt
      - ./dep/activator:/root/.activator
      - ./dep/m2:/root/.m2
    ports:
      - 8080:8080 # core
      - 9000:9000 # ui
      - 9999:9999 # ui jvm-debug
      - 8983:8983 # solr
    command: /bin/bash
    tty: yes